#version: "3.8" 

services:
  database:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fraud_detection
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    depends_on:
      - database
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@database/fraud_detection
    ports:
      - "8000:8000"
    entrypoint: [
        "./wait-for-it.sh",
        "database:5432",
        "--timeout=30", 
        "--", 
        "uvicorn",
        "main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
      ]
    volumes:
      - ./backend:/app 

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
